version: '3.8'

services:
  psql-db:
    image: postgres:latest
    container_name: psql-db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${LOCAL_DB_PORT}:5432"

  api:
    container_name: api_app
    build:
      context: .
      dockerfile: Dockerfile_debug
    image: simple-photo-sharing-platform-api
    volumes:
      - type: bind
        source: ./src
        target: /opt/app/src
    env_file:
      - .env
      - .aws-credentials
    ports:
      - "${LOCAL_APP_PORT}:8080"
    depends_on:
      - psql-db
    command: [ "./mvnw", "spring-boot:run" ]

volumes:
  db-data:
    driver: local