services:
  server-api:
    container_name: server-api
    image: xamarsia/spsp-server:2.0.0
    env_file:
      - ./.env
      - ./.minio-credentials
    ports:
      - 8080:8080
    networks:
      - external_network
      - db_network

  psql-db:
    container_name: psql-db
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db_network

  minio-db:
    container_name: minio-db
    image: minio/minio:latest
    ports:
      - "9000:9000" # file upload&preview port
      - "9001:9001" # console access port
    restart: always
    env_file:
      - ./.minio-credentials
    volumes:
      - "minio-data:/data"
    networks:
      - db_network
    command: server /data  --console-address ":9001"

volumes:
  db-data:
  minio-data:

networks:
  external_network:
    name: microservice_network
    external: true
  db_network:
