spring:
  application:
    name: book-storage
  datasource:
    url: jdbc:postgresql://psql-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

aws:
  region: ca-central-1
  s3:
    buckets:
      posts: "spsp-post-images"
      profiles: "spsp-profile-images"

application:
  security:
    token-type: "Bearer "
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*,Authorization"
