spring:
  application:
    name: photo-sharing-platform
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/${PUBLIC_FIREBASE_PROJECT_ID}
  datasource:
    url: jdbc:postgresql://psql-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baseline-description: "init"
    baseline-version: 0

minio:
  region: ${MINIO_REGION}
  endpoint: http://minio-db:9000/
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  buckets:
    posts: ${MINIO_POSTS_BUCKET_NAME}
    profiles: ${MINIO_PROFILE_BUCKET_NAME}

application:
  security:
    token-type: "Bearer "
    cors:
      allowed-origins: "http://localhost:3000,http://${DOMAIN_NAME},https://${DOMAIN_NAME}"
      allowed-methods: "GET,POST"
      allowed-headers: "*,Authorization"
    authentication-filter:
      excludedUrl: "/auth/**,/post/**,/user/**"
