version: '3.7'
services:
  server-api:
    container_name: server-api
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-photo-sharing-platform-api
    env_file:
      - ../.env
      # - ../.aws-credentials
      - ../.minio-credentials
    ports:
      - 8080:8080
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - external_network
      - db_network

  psql-db:
    container_name: psql-db
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    # restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db_network

  minio-db:
    container_name: minio-db
    image: minio/minio:latest
    ports:
      - "9000:9000" # file upload&preview port
      - "9001:9001" # console access port
    # restart: always
    restart: unless-stopped
    env_file:
      - ../.minio-credentials
    volumes:
      - "minio-data:/data"
    networks:
      - db_network
    command: server /data  --console-address ":9001"
    # command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    expose:
      - "9000"
      - "9001"

volumes:
  db-data:
  minio-data:
    # driver: local

networks:
  external_network:
    name: microservice_network
    external: true
  db_network:
