version: "3.8"

services:
  api:
    container_name: dev-api
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-photo-sharing-platform-api
    env_file:
      - ../.env
      - ../.aws-credentials
    ports:
      - 8080:8080
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - external_network
      - db_network

  psql-db:
    container_name: psql-db
    image: postgres:latest
    ports:
      - 5432:5432
    # restart: always
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  db-data:

networks:
  external_network:
    name: microservice_network
    external: true
  db_network:
